#!/bin/bash

./node_modules/.bin/webpack -p

scp index.html pi@192.168.0.14:/var/www/html/react-app
scp bundle.js pi@192.168.0.14:/var/www/html/react-app
scp -r backend/ pi@192.168.0.14:/var/www/html/react-app
