export const FETCH_DEPARTURES_DATA = 'FETCH_DEPARTURES_DATA';
export const FETCH_DEPARTURES_DATA_SUCCEEDED = 'FETCH_DEPARTURES_DATA_SUCCEEDED';
export const FETCH_DEPARTURES_DATA_FAILED = 'FETCH_DEPARTURES_DATA_FAILED';
